Cargo.toml
orchestra/Cargo.toml

After the [infinite quest of remote signing is resolved](https://hachyderm.io/@drahnr/109760070036729749), let's release `v0.0.5`

release: v0.0.5

---

orchestra/proc-macro/src/impl_orchestra.rs

Remove unused const

---

orchestra/proc-macro/src/impl_orchestra.rs
orchestra/src/lib.rs

This small PR addresses the following issue: https://github.com/paritytech/polkadot/issues/6710
It is quite useful to understand what specific signal/message has caused the stall.

Be more specific about stall reason

---

Cargo.lock
metered-channel/Cargo.toml
metered-channel/src/bounded.rs
metered-channel/src/lib.rs
metered-channel/src/tests.rs
orchestra/proc-macro/src/impl_orchestra.rs
orchestra/src/lib.rs

This PR provides the ad-hoc replacement for the inner bounded channel from `futures::mpsc` to `async_channel::bounded`. The former channel is based on the shared memory ring that provides benefits in terms of latency and throughput. This PR also removes the requirement for the consumers to implement `From<mpsc::SendError>` as now it is returned as `OrchestraError::QueueError` transparently. There should be no API breaking to my best knowledge.

Switch mettered inner to the async-channel

---

README.md
orchestra/proc-macro/Cargo.toml
orchestra/proc-macro/src/impl_builder.rs
orchestra/proc-macro/src/impl_channels_out.rs
orchestra/proc-macro/src/impl_orchestra.rs
orchestra/proc-macro/src/parse/mod.rs
orchestra/proc-macro/src/parse/parse_cfg.rs
orchestra/proc-macro/src/parse/parse_orchestra_struct.rs

In this PR I introduce guarding of subsystems via features.
Supported syntax:
```rust
#[orchestra(signal=Signal, event=ExternalEvent, error=SubsystemError, gen=AllMessages)]
struct MyOverseer<T, U, V, W> {
#[cfg(feature = "feature1")]
#[subsystem(consumes: Subsystem1Message, sends: [Subsystem2Message])]
subsystem1: Sub1,
#[subsystem(consumes: Subsystem2Message, sends: [Subsystem1Message])]
subsystem2: Sub2,
}
```
Basically this allows re-use of one orchestra in scenarios where it is not needed to run all subsystems. The `#cfg` attribute macro currently supports `any`, `all`, `not` and `feature = "something"`.
- Feature unification. The current implementation is not very useful when you have a large workspace, and different crates depend on the defined orchestra with different features …

Feature gating subsystems via `#[cfg]`

---

metered-channel/src/bounded.rs
metered-channel/src/tests.rs
orchestra/examples/duo.rs
orchestra/proc-macro/src/impl_channels_out.rs
orchestra/proc-macro/src/impl_message_wrapper.rs
orchestra/proc-macro/src/impl_orchestra.rs
orchestra/proc-macro/src/impl_subsystem_ctx_sender.rs
orchestra/src/lib.rs

This PR addresses #44. WIP currently:

Add try_send method to the orchestra output channels

---

README.md
orchestra/src/lib.rs

Minor documentation addition on caveats

feat: docs and clippy chores

---

orchestra/proc-macro/src/impl_orchestra.rs
orchestra/src/lib.rs

This PR addresses #18
Rough architecture description.
1) We first try to send signals via `try_send_signal` for each subsystem. This is not an async function and it is blazingly fast for the vast majority of the cases. So it is a fast path.
2) If some subsystem is slow, then we create a new future where we perform the real async `send_signal` function.
3) These futures are joint in `FuturesUnordered` to allow unordered polling. When some subsystem gets ready to accept a signal it immediately receives that signal.
With such an approach, we do not create unnecessary futures nor vectors of futures and we just utilise the fast path via `try_send` in the majority of this function calls.

Send signals in parallel

---

.github/workflows/rust.yml
Cargo.lock
Cargo.toml
metered-channel/Cargo.toml
metered-channel/src/bounded.rs
metered-channel/src/lib.rs
metered-channel/src/tests.rs
metered-channel/src/unbounded.rs
orchestra/Cargo.toml
orchestra/proc-macro/src/impl_orchestra.rs
orchestra/src/lib.rs

This PR addresses the compatibility issue: it is still impossible to use `async-channel` in Polkadot for some reasons. So far, we have no full understanding why does this happen but we want to be able to sync with the recent orchestra updates. With this change, it will be possible to select the concrete implementation of the underlying channels via features. Well, cargo features has proven to be a fragile and poor choice for it but it is complie time, so it has no cost on operations.
This PR is stacked with #47

Allow to use both async-channel and futures channels via feature flags

---

Cargo.lock
README.md
metered-channel/Cargo.toml
orchestra/Cargo.toml
orchestra/proc-macro/Cargo.toml
orchestra/proc-macro/src/graph.rs
orchestra/proc-macro/src/impl_subsystem_ctx_sender.rs
orchestra/proc-macro/src/lib.rs

~~The generated files are far from perfect, `layout-rs` is not working out too well..~~
The generated files only deviate in the sense that double circles are not rendered accurately, otherwise the output looks fine.
The `png` rendered lacks text render capabilities, and is hence feature gated for now.

feat/dotgraph: implement dot graph rendering as part of the proc-macro

---

metered-channel/Cargo.toml
metered-channel/src/bounded.rs
orchestra/Cargo.toml

#48 introduced aliasing error types, but didn't provide publicly acessible `From<_>` implementations. This PR adds those and makes use of them internally.

feat: add convenience conversion for TrySend error

---

Cargo.toml
orchestra/proc-macro/src/impl_orchestra.rs

When building polkadot with the recent orchestra I have revealed that the build fails on a very late stage (when linking the service), as orchestra does not explicitly specifies that signals waiting futures are `Send`. The goal of this PR is to fix this issue...

Add missing traits to avoid compilation issues

---

Cargo.lock
metered-channel/src/bounded.rs

Adds more transforms for generalized test harness support in our codebase. It's just a pain to have match statements when I really want to transform the inner value of both enum variants. Technically we might want to consider to move to a `struct` + flat + `enum`-kind type approach, but that's for later I guess.

chore: more transforms

---

metered-channel/src/bounded.rs
metered-channel/src/lib.rs
metered-channel/src/tests.rs
metered-channel/src/unbounded.rs

Currently we use prometheus query to measure channel size but this is notoriously inaccurate, especially when scrapers are under high load.
For `async_channel`, `len()` is supported, but for `futures_channel` we compute it based on sent/received.

Add meter for channel len

---

orchestra/proc-macro/src/graph.rs
orchestra/proc-macro/tests/assets/sample.dot

Due to https://github.com/nadavrot/layout/issues/19 conversion of the dot graph to svg fails, and currently prevents writing both to disk, although the prior would be available.

fix/dotgraph: write dot graph even if conversion to svg fails

---

metered-channel/src/bounded.rs
metered-channel/src/lib.rs

This is a simple fine tune for a metered channel to update channel length merely when we need a readout.
There are two other small changes:
* Implement `len` method for the `futures_channel` feature flag
* Fix inconsistency between documentation and the actual value for the TOF queue size

Avoid writing length on each IO for async channel

---

Cargo.lock
metered-channel/Cargo.toml
metered-channel/src/bounded.rs
metered-channel/src/lib.rs
metered-channel/src/tests.rs
orchestra/Cargo.toml

This PR adds `_priority` set of methods to send messages over channels with higher priority.
TODO: document the logic and add proc-macro support to the orchestra

Add priorities support for the bounded metered channels

---

Cargo.lock
orchestra/Cargo.toml
orchestra/examples/backpressure.rs
orchestra/proc-macro/src/impl_subsystem_ctx_sender.rs
orchestra/src/lib.rs

Closes #65 
It's a draft. Race conditions still have to be evaluated. Probably, a better synchronization model is needed. Proper documentation is still lacking, as well.

Implement separate signal and message flows

---

orchestra/proc-macro/src/impl_subsystem_ctx_sender.rs

We forgot to increment signals_received, that make subsystems to fall out of sync if they start using recv_signal, which we did in https://github.com/paritytech/polkadot-sdk/pull/2125 and that made roco to slow-down significantly.

fixup! Implement separate signal and message flows (#66)

---

Cargo.lock
orchestra/proc-macro/Cargo.toml

Needed for https://github.com/paritytech/polkadot-sdk/pull/4409

Bump `proc-macro-crate` to v 3.1.0

---

Cargo.lock

Expander was bumped in https://github.com/paritytech/orchestra/pull/74, but locked version wasn't updated

Update locked expander version

---

Cargo.lock
Cargo.toml
orchestra/Cargo.toml
orchestra/proc-macro/src/impl_channels_out.rs
orchestra/proc-macro/src/impl_subsystem_ctx_sender.rs

Fixes https://github.com/paritytech/orchestra/issues/80
v0.3.7 requires importing of priority related structs what conflicts with the definition of a *patch* version 
In this PR priority related structs prefixed with `#support_crate ::` that points to otchestra so it doesn't require the explicit import to use `#[subsystem]`. 
However if the `Sender` trait is used it still requires to implement new methods `send_message_with_priority` and `try_send_message_with_priority`. This PR https://github.com/paritytech/polkadot-sdk/pull/4763/ shows required changes.
So I suggest bumping the library to v0.4.0. v0.3.7 should be yanked.

Fix using unimported priority structs

---

orchestra/proc-macro/src/impl_orchestra.rs
orchestra/src/lib.rs

Extend round_message to be able to route messages based on the priority of the message, this will be used in the overseer to send messages with high priority for https://github.com/paritytech/polkadot-sdk/issues/8830.

make it possible to route messages based on priority
